version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - 15672:15672

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/family-config
    restart: on-failure

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/family-registry
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:3000

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/family-gateway
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: aydarik/family-auth-service
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: aydarik/family-mongodb
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      ACCOUNT_SERVICE_PASSWORD: $ACCOUNT_SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: aydarik/family-account-service
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: aydarik/family-mongodb
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: aydarik/family-monitoring
    restart: on-failure
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
      - 8989:8989