spring:
  datasource:
    url: ${MYSQL_PATH}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
#    generate-ddl: true
#    show-sql=true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update

server:
  context-path: /uaa
  port: 5000
