security:
  oauth2:
    client:
      clientId: eth-service
      clientSecret: ${ETHEREUM_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

feign:
  hystrix:
    enabled: true

server:
  context-path: /ethereum
  port: 7000

infura:
  network: rinkeby
  key: ${INFURA_API_KEY}